name: Experimental Release
on:
  push:
    branches:
      - main
      - bugfix/**
      - feature/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v3
      - name: Do Versioning
        run: |
          Install-Module ChangelogManagement -Force

          $Changelogs = Get-ChildItem -Path $env:GITHUB_WORKSPACE -Filter "CHANGELOG.md" -Recurse
          Write-Host $Changelogs

          foreach ($Changelog in $Changelogs) {
            $Data = Get-ChangelogData -Path $Changelog.FullName
            if ($Data.Unreleased.RawData) {
              Write-Host "$Changelog is ready to be released"
            } else {
              Write-Host "$Changelog does not need released"
            }
          }
