name: "Release dev container features & Generate Documentation"
on:
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v3
      - name: Validate Changelogs & Version Numbers
        run: |
          Install-Module ChangelogManagement -Force

          $Changelogs = Get-ChildItem -Path $env:GITHUB_WORKSPACE -Filter "CHANGELOG.md" -Recurse

          foreach ($Changelog in $Changelogs) {
            $Data = Get-ChangelogData -Path $Changelog.FullName
            $BasePath = Split-Path -Path $Changelog.FullName -Parent
            $JsonPath = Join-Path $BasePath "devcontainer-feature.json"
            $JsonData = Get-Content -Path $JsonPath -Raw | ConvertFrom-Json -Depth 100
            $JsonVersion = $JsonData.version
            if ($Data.Unreleased.ChangeCount -gt 0) {
              if ([System.Management.Automation.SemanticVersion]$JsonVersion -gt [System.Management.Automation.SemanticVersion]$Data.LastVersion) {
                Write-Host "'$JsonPath' contains a valid version number '$JsonVersion'."
              } else {
                throw "Changes exist in Changelog, but version number in '$JsonPath' needs increased in order to release."
              }

              Write-Host "Updating Changelog '$($Changelog.FullName)'..."
              Update-Changelog -Path $Changelog.FullName -ReleaseVersion $JsonVersion -LinkMode None
            } else {
              if ([System.Management.Automation.SemanticVersion]$JsonVersion -gt [System.Management.Automation.SemanticVersion]$Data.LastVersion) {
                throw "'$JsonPath' contains a valid version for release, but there are no changes in '$($Changelog.FullName)'."
              }
            }
          }
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          commit-message: Release ${{ github.run_id }}
          branch: release/${{ github.run_id }}
          delete-branch: true
          title: Release ${{ github.run_id }}
      - name: Publish Features
        uses: devcontainers/action@v1
        with:
          publish-features: true
          base-path-to-features: ./src
          generate-docs: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
