name: Experimental Release
on:
  push:
    branches:
      - main
      - bugfix/**
      - feature/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v3
      - name: Do Versioning
        run: |
          Install-Module ChangelogManagement -Force
          Install-Module SemVer -Force

          $Changelogs = Get-ChildItem -Path $env:GITHUB_WORKSPACE -Filter "CHANGELOG.md" -Recurse
          Write-Host $Changelogs

          foreach ($Changelog in $Changelogs) {
            $Data = Get-ChangelogData -Path $Changelog.FullName
            if ($Data.Unreleased.RawData) {
              $BasePath = Split-Path -Path $Changelog.FullName -Parent
              $JsonPath = Join-Path $BasePath "devcontainer-feature.json"
              Write-Host "'$JsonPath' needs updated for release..." -Color Green
              $JsonData = Get-Content -Path $JsonPath -Raw | ConvertFrom-Json -Depth 100
              Write-Host "Current Version for '$JsonPath' is $($JsonData.version)" -ForegroundColor Cyan
              $NewVersion = Update-Version -ver $JsonData.version
              Write-Host "New Version for '$Jsonpath' is $NewVersion" -ForegroundColor Cyan
            }
          }
